// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/mission/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMissionV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMissionV1alpha1) Missions(namespace string) v1alpha1.MissionInterface {
	return &FakeMissions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMissionV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
