##
## Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
##
## This file is part of ewm-cloud-robotics
## (see https://github.com/SAP/ewm-cloud-robotics).
##
## This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
##

git:
  depth: 1

install:
  - echo "SKIP."

stages:
  - name: ewm-sim-node-tests
  - name: scan-modules
  - name: release
    if: tag =~ /(^v?[0-9]+(\.[0-9]+)+)((-.*)|$)/

jobs:  
  include:
    ## ewm-sim-node-tests
    - stage: ewm-sim-node-tests
      name: "ewm-sim mocha tests"
      language: node_js
      node_js:
      - 14.15.0
      install:
      - cd docker/ewm-sim
      - npm install
      script:
      - npm run test
      after_success:
      - npm run coverage
    ## scan-modules
    - stage: scan-modules
      name: "WhiteSource Scans"
      language: python
      dist: xenial
      python: "3.7"
      services:
        - docker
      script: sh ./scripts/whitesource.sh
    - stage: scan-modules
      name: "Bandit Scans"
      language: python
      dist: xenial
      python: "3.7"
      services:
        - docker
      script: sh ./scripts/bandit.sh    
    ## release-images
    - stage: release
      name: "Docker Image Releases"
      language: python
      dist: xenial
      python: "3.7"
      services:
        - docker
      script: sh ./ci/release.sh
