apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot-configurator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sap-ewm:robot-configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sap-ewm:robot-configurator
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: robot-configurator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: robot-controller-cloud
spec:
  replicas: 1
  serviceName: robot-controller-cloud
  selector:
    matchLabels:
      app: robot-controller-cloud
  template:
    metadata:
      labels:
        app: robot-controller-cloud
    spec:
      serviceAccountName: robot-configurator
      containers:
      - image: {{ $.Values.image }}
        name: robot-controller
        env:
        - name: ROBOTS
          value: "{{- range $.Values.robots }}{{ .name }},{{- end }}"
        - name: MAX_RETRY_COUNT
          value: "{{ $.Values.envs.maxretrycount }}"
        - name: LOG_LEVEL
          value: {{ $.Values.envs.log.level }}
        - name: LOG_FORMAT
          value: {{ $.Values.envs.log.format }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "1200m"
---
apiVersion: v1
kind: Service
metadata:
  name: robot-controller-cloud
  labels:
    app: robot-controller-cloud
spec:
  ports:
  - name: metrics
    port: 8000
  selector:
    app: robot-controller-cloud
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robot-controller-cloud
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: robot-controller-cloud
