// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	scheme "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuctioneerRequestsGetter has a method to return a AuctioneerRequestInterface.
// A group's client should implement this interface.
type AuctioneerRequestsGetter interface {
	AuctioneerRequests(namespace string) AuctioneerRequestInterface
}

// AuctioneerRequestInterface has methods to work with AuctioneerRequest resources.
type AuctioneerRequestInterface interface {
	Create(*v1alpha1.AuctioneerRequest) (*v1alpha1.AuctioneerRequest, error)
	Update(*v1alpha1.AuctioneerRequest) (*v1alpha1.AuctioneerRequest, error)
	UpdateStatus(*v1alpha1.AuctioneerRequest) (*v1alpha1.AuctioneerRequest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AuctioneerRequest, error)
	List(opts v1.ListOptions) (*v1alpha1.AuctioneerRequestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuctioneerRequest, err error)
	AuctioneerRequestExpansion
}

// auctioneerRequests implements AuctioneerRequestInterface
type auctioneerRequests struct {
	client rest.Interface
	ns     string
}

// newAuctioneerRequests returns a AuctioneerRequests
func newAuctioneerRequests(c *EwmV1alpha1Client, namespace string) *auctioneerRequests {
	return &auctioneerRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the auctioneerRequest, and returns the corresponding auctioneerRequest object, and an error if there is any.
func (c *auctioneerRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.AuctioneerRequest, err error) {
	result = &v1alpha1.AuctioneerRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AuctioneerRequests that match those selectors.
func (c *auctioneerRequests) List(opts v1.ListOptions) (result *v1alpha1.AuctioneerRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AuctioneerRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested auctioneerRequests.
func (c *auctioneerRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a auctioneerRequest and creates it.  Returns the server's representation of the auctioneerRequest, and an error, if there is any.
func (c *auctioneerRequests) Create(auctioneerRequest *v1alpha1.AuctioneerRequest) (result *v1alpha1.AuctioneerRequest, err error) {
	result = &v1alpha1.AuctioneerRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		Body(auctioneerRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a auctioneerRequest and updates it. Returns the server's representation of the auctioneerRequest, and an error, if there is any.
func (c *auctioneerRequests) Update(auctioneerRequest *v1alpha1.AuctioneerRequest) (result *v1alpha1.AuctioneerRequest, err error) {
	result = &v1alpha1.AuctioneerRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		Name(auctioneerRequest.Name).
		Body(auctioneerRequest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *auctioneerRequests) UpdateStatus(auctioneerRequest *v1alpha1.AuctioneerRequest) (result *v1alpha1.AuctioneerRequest, err error) {
	result = &v1alpha1.AuctioneerRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		Name(auctioneerRequest.Name).
		SubResource("status").
		Body(auctioneerRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the auctioneerRequest and deletes it. Returns an error if one occurs.
func (c *auctioneerRequests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *auctioneerRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auctioneerrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched auctioneerRequest.
func (c *auctioneerRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuctioneerRequest, err error) {
	result = &v1alpha1.AuctioneerRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("auctioneerrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
