// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	scheme "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuctioneersGetter has a method to return a AuctioneerInterface.
// A group's client should implement this interface.
type AuctioneersGetter interface {
	Auctioneers(namespace string) AuctioneerInterface
}

// AuctioneerInterface has methods to work with Auctioneer resources.
type AuctioneerInterface interface {
	Create(*v1alpha1.Auctioneer) (*v1alpha1.Auctioneer, error)
	Update(*v1alpha1.Auctioneer) (*v1alpha1.Auctioneer, error)
	UpdateStatus(*v1alpha1.Auctioneer) (*v1alpha1.Auctioneer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Auctioneer, error)
	List(opts v1.ListOptions) (*v1alpha1.AuctioneerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Auctioneer, err error)
	AuctioneerExpansion
}

// auctioneers implements AuctioneerInterface
type auctioneers struct {
	client rest.Interface
	ns     string
}

// newAuctioneers returns a Auctioneers
func newAuctioneers(c *EwmV1alpha1Client, namespace string) *auctioneers {
	return &auctioneers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the auctioneer, and returns the corresponding auctioneer object, and an error if there is any.
func (c *auctioneers) Get(name string, options v1.GetOptions) (result *v1alpha1.Auctioneer, err error) {
	result = &v1alpha1.Auctioneer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auctioneers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Auctioneers that match those selectors.
func (c *auctioneers) List(opts v1.ListOptions) (result *v1alpha1.AuctioneerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AuctioneerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auctioneers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested auctioneers.
func (c *auctioneers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("auctioneers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a auctioneer and creates it.  Returns the server's representation of the auctioneer, and an error, if there is any.
func (c *auctioneers) Create(auctioneer *v1alpha1.Auctioneer) (result *v1alpha1.Auctioneer, err error) {
	result = &v1alpha1.Auctioneer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("auctioneers").
		Body(auctioneer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a auctioneer and updates it. Returns the server's representation of the auctioneer, and an error, if there is any.
func (c *auctioneers) Update(auctioneer *v1alpha1.Auctioneer) (result *v1alpha1.Auctioneer, err error) {
	result = &v1alpha1.Auctioneer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("auctioneers").
		Name(auctioneer.Name).
		Body(auctioneer).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *auctioneers) UpdateStatus(auctioneer *v1alpha1.Auctioneer) (result *v1alpha1.Auctioneer, err error) {
	result = &v1alpha1.Auctioneer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("auctioneers").
		Name(auctioneer.Name).
		SubResource("status").
		Body(auctioneer).
		Do().
		Into(result)
	return
}

// Delete takes name of the auctioneer and deletes it. Returns an error if one occurs.
func (c *auctioneers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auctioneers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *auctioneers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auctioneers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched auctioneer.
func (c *auctioneers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Auctioneer, err error) {
	result = &v1alpha1.Auctioneer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("auctioneers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
