// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AuctioneerExpansion interface{}

type AuctioneerRequestExpansion interface{}

type OrderAuctionExpansion interface{}

type RobotConfigurationExpansion interface{}

type RobotRequestExpansion interface{}

type WarehouseOrderExpansion interface{}
