// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	scheme "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OrderAuctionsGetter has a method to return a OrderAuctionInterface.
// A group's client should implement this interface.
type OrderAuctionsGetter interface {
	OrderAuctions(namespace string) OrderAuctionInterface
}

// OrderAuctionInterface has methods to work with OrderAuction resources.
type OrderAuctionInterface interface {
	Create(*v1alpha1.OrderAuction) (*v1alpha1.OrderAuction, error)
	Update(*v1alpha1.OrderAuction) (*v1alpha1.OrderAuction, error)
	UpdateStatus(*v1alpha1.OrderAuction) (*v1alpha1.OrderAuction, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.OrderAuction, error)
	List(opts v1.ListOptions) (*v1alpha1.OrderAuctionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OrderAuction, err error)
	OrderAuctionExpansion
}

// orderAuctions implements OrderAuctionInterface
type orderAuctions struct {
	client rest.Interface
	ns     string
}

// newOrderAuctions returns a OrderAuctions
func newOrderAuctions(c *EwmV1alpha1Client, namespace string) *orderAuctions {
	return &orderAuctions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the orderAuction, and returns the corresponding orderAuction object, and an error if there is any.
func (c *orderAuctions) Get(name string, options v1.GetOptions) (result *v1alpha1.OrderAuction, err error) {
	result = &v1alpha1.OrderAuction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("orderauctions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OrderAuctions that match those selectors.
func (c *orderAuctions) List(opts v1.ListOptions) (result *v1alpha1.OrderAuctionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OrderAuctionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("orderauctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested orderAuctions.
func (c *orderAuctions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("orderauctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a orderAuction and creates it.  Returns the server's representation of the orderAuction, and an error, if there is any.
func (c *orderAuctions) Create(orderAuction *v1alpha1.OrderAuction) (result *v1alpha1.OrderAuction, err error) {
	result = &v1alpha1.OrderAuction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("orderauctions").
		Body(orderAuction).
		Do().
		Into(result)
	return
}

// Update takes the representation of a orderAuction and updates it. Returns the server's representation of the orderAuction, and an error, if there is any.
func (c *orderAuctions) Update(orderAuction *v1alpha1.OrderAuction) (result *v1alpha1.OrderAuction, err error) {
	result = &v1alpha1.OrderAuction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("orderauctions").
		Name(orderAuction.Name).
		Body(orderAuction).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *orderAuctions) UpdateStatus(orderAuction *v1alpha1.OrderAuction) (result *v1alpha1.OrderAuction, err error) {
	result = &v1alpha1.OrderAuction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("orderauctions").
		Name(orderAuction.Name).
		SubResource("status").
		Body(orderAuction).
		Do().
		Into(result)
	return
}

// Delete takes name of the orderAuction and deletes it. Returns an error if one occurs.
func (c *orderAuctions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("orderauctions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *orderAuctions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("orderauctions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched orderAuction.
func (c *orderAuctions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OrderAuction, err error) {
	result = &v1alpha1.OrderAuction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("orderauctions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
