// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	scheme "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RobotRequestsGetter has a method to return a RobotRequestInterface.
// A group's client should implement this interface.
type RobotRequestsGetter interface {
	RobotRequests(namespace string) RobotRequestInterface
}

// RobotRequestInterface has methods to work with RobotRequest resources.
type RobotRequestInterface interface {
	Create(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.CreateOptions) (*v1alpha1.RobotRequest, error)
	Update(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.UpdateOptions) (*v1alpha1.RobotRequest, error)
	UpdateStatus(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.UpdateOptions) (*v1alpha1.RobotRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RobotRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RobotRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RobotRequest, err error)
	RobotRequestExpansion
}

// robotRequests implements RobotRequestInterface
type robotRequests struct {
	client rest.Interface
	ns     string
}

// newRobotRequests returns a RobotRequests
func newRobotRequests(c *EwmV1alpha1Client, namespace string) *robotRequests {
	return &robotRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the robotRequest, and returns the corresponding robotRequest object, and an error if there is any.
func (c *robotRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RobotRequests that match those selectors.
func (c *robotRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RobotRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RobotRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested robotRequests.
func (c *robotRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a robotRequest and creates it.  Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *robotRequests) Create(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.CreateOptions) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(robotRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a robotRequest and updates it. Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *robotRequests) Update(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.UpdateOptions) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(robotRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(robotRequest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *robotRequests) UpdateStatus(ctx context.Context, robotRequest *v1alpha1.RobotRequest, opts v1.UpdateOptions) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(robotRequest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(robotRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the robotRequest and deletes it. Returns an error if one occurs.
func (c *robotRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *robotRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched robotRequest.
func (c *robotRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("robotrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
