// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	scheme "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RobotRequestsGetter has a method to return a RobotRequestInterface.
// A group's client should implement this interface.
type RobotRequestsGetter interface {
	RobotRequests(namespace string) RobotRequestInterface
}

// RobotRequestInterface has methods to work with RobotRequest resources.
type RobotRequestInterface interface {
	Create(*v1alpha1.RobotRequest) (*v1alpha1.RobotRequest, error)
	Update(*v1alpha1.RobotRequest) (*v1alpha1.RobotRequest, error)
	UpdateStatus(*v1alpha1.RobotRequest) (*v1alpha1.RobotRequest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RobotRequest, error)
	List(opts v1.ListOptions) (*v1alpha1.RobotRequestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RobotRequest, err error)
	RobotRequestExpansion
}

// robotRequests implements RobotRequestInterface
type robotRequests struct {
	client rest.Interface
	ns     string
}

// newRobotRequests returns a RobotRequests
func newRobotRequests(c *EwmV1alpha1Client, namespace string) *robotRequests {
	return &robotRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the robotRequest, and returns the corresponding robotRequest object, and an error if there is any.
func (c *robotRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RobotRequests that match those selectors.
func (c *robotRequests) List(opts v1.ListOptions) (result *v1alpha1.RobotRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RobotRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested robotRequests.
func (c *robotRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a robotRequest and creates it.  Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *robotRequests) Create(robotRequest *v1alpha1.RobotRequest) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("robotrequests").
		Body(robotRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a robotRequest and updates it. Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *robotRequests) Update(robotRequest *v1alpha1.RobotRequest) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(robotRequest.Name).
		Body(robotRequest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *robotRequests) UpdateStatus(robotRequest *v1alpha1.RobotRequest) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(robotRequest.Name).
		SubResource("status").
		Body(robotRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the robotRequest and deletes it. Returns an error if one occurs.
func (c *robotRequests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robotrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *robotRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robotrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched robotRequest.
func (c *robotRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RobotRequest, err error) {
	result = &v1alpha1.RobotRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("robotrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
