// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/ewm/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeEwmV1alpha1 struct {
	*testing.Fake
}

func (c *FakeEwmV1alpha1) Auctioneers(namespace string) v1alpha1.AuctioneerInterface {
	return &FakeAuctioneers{c, namespace}
}

func (c *FakeEwmV1alpha1) AuctioneerRequests(namespace string) v1alpha1.AuctioneerRequestInterface {
	return &FakeAuctioneerRequests{c, namespace}
}

func (c *FakeEwmV1alpha1) OrderAuctions(namespace string) v1alpha1.OrderAuctionInterface {
	return &FakeOrderAuctions{c, namespace}
}

func (c *FakeEwmV1alpha1) RobotConfigurations(namespace string) v1alpha1.RobotConfigurationInterface {
	return &FakeRobotConfigurations{c, namespace}
}

func (c *FakeEwmV1alpha1) RobotRequests(namespace string) v1alpha1.RobotRequestInterface {
	return &FakeRobotRequests{c, namespace}
}

func (c *FakeEwmV1alpha1) WarehouseOrders(namespace string) v1alpha1.WarehouseOrderInterface {
	return &FakeWarehouseOrders{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEwmV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
