// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOrderReservations implements OrderReservationInterface
type FakeOrderReservations struct {
	Fake *FakeEwmV1alpha1
	ns   string
}

var orderreservationsResource = schema.GroupVersionResource{Group: "ewm.sap.com", Version: "v1alpha1", Resource: "orderreservations"}

var orderreservationsKind = schema.GroupVersionKind{Group: "ewm.sap.com", Version: "v1alpha1", Kind: "OrderReservation"}

// Get takes name of the orderReservation, and returns the corresponding orderReservation object, and an error if there is any.
func (c *FakeOrderReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OrderReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(orderreservationsResource, c.ns, name), &v1alpha1.OrderReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderReservation), err
}

// List takes label and field selectors, and returns the list of OrderReservations that match those selectors.
func (c *FakeOrderReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OrderReservationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(orderreservationsResource, orderreservationsKind, c.ns, opts), &v1alpha1.OrderReservationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OrderReservationList{ListMeta: obj.(*v1alpha1.OrderReservationList).ListMeta}
	for _, item := range obj.(*v1alpha1.OrderReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested orderReservations.
func (c *FakeOrderReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(orderreservationsResource, c.ns, opts))

}

// Create takes the representation of a orderReservation and creates it.  Returns the server's representation of the orderReservation, and an error, if there is any.
func (c *FakeOrderReservations) Create(ctx context.Context, orderReservation *v1alpha1.OrderReservation, opts v1.CreateOptions) (result *v1alpha1.OrderReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(orderreservationsResource, c.ns, orderReservation), &v1alpha1.OrderReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderReservation), err
}

// Update takes the representation of a orderReservation and updates it. Returns the server's representation of the orderReservation, and an error, if there is any.
func (c *FakeOrderReservations) Update(ctx context.Context, orderReservation *v1alpha1.OrderReservation, opts v1.UpdateOptions) (result *v1alpha1.OrderReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(orderreservationsResource, c.ns, orderReservation), &v1alpha1.OrderReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderReservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOrderReservations) UpdateStatus(ctx context.Context, orderReservation *v1alpha1.OrderReservation, opts v1.UpdateOptions) (*v1alpha1.OrderReservation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(orderreservationsResource, "status", c.ns, orderReservation), &v1alpha1.OrderReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderReservation), err
}

// Delete takes name of the orderReservation and deletes it. Returns an error if one occurs.
func (c *FakeOrderReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(orderreservationsResource, c.ns, name), &v1alpha1.OrderReservation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOrderReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(orderreservationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OrderReservationList{})
	return err
}

// Patch applies the patch and returns the patched orderReservation.
func (c *FakeOrderReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OrderReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(orderreservationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.OrderReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderReservation), err
}
