// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRobotRequests implements RobotRequestInterface
type FakeRobotRequests struct {
	Fake *FakeEwmV1alpha1
	ns   string
}

var robotrequestsResource = schema.GroupVersionResource{Group: "ewm.sap.com", Version: "v1alpha1", Resource: "robotrequests"}

var robotrequestsKind = schema.GroupVersionKind{Group: "ewm.sap.com", Version: "v1alpha1", Kind: "RobotRequest"}

// Get takes name of the robotRequest, and returns the corresponding robotRequest object, and an error if there is any.
func (c *FakeRobotRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.RobotRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(robotrequestsResource, c.ns, name), &v1alpha1.RobotRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RobotRequest), err
}

// List takes label and field selectors, and returns the list of RobotRequests that match those selectors.
func (c *FakeRobotRequests) List(opts v1.ListOptions) (result *v1alpha1.RobotRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(robotrequestsResource, robotrequestsKind, c.ns, opts), &v1alpha1.RobotRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RobotRequestList{ListMeta: obj.(*v1alpha1.RobotRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.RobotRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested robotRequests.
func (c *FakeRobotRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(robotrequestsResource, c.ns, opts))

}

// Create takes the representation of a robotRequest and creates it.  Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *FakeRobotRequests) Create(robotRequest *v1alpha1.RobotRequest) (result *v1alpha1.RobotRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(robotrequestsResource, c.ns, robotRequest), &v1alpha1.RobotRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RobotRequest), err
}

// Update takes the representation of a robotRequest and updates it. Returns the server's representation of the robotRequest, and an error, if there is any.
func (c *FakeRobotRequests) Update(robotRequest *v1alpha1.RobotRequest) (result *v1alpha1.RobotRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(robotrequestsResource, c.ns, robotRequest), &v1alpha1.RobotRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RobotRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRobotRequests) UpdateStatus(robotRequest *v1alpha1.RobotRequest) (*v1alpha1.RobotRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(robotrequestsResource, "status", c.ns, robotRequest), &v1alpha1.RobotRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RobotRequest), err
}

// Delete takes name of the robotRequest and deletes it. Returns an error if one occurs.
func (c *FakeRobotRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(robotrequestsResource, c.ns, name), &v1alpha1.RobotRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRobotRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(robotrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RobotRequestList{})
	return err
}

// Patch applies the patch and returns the patched robotRequest.
func (c *FakeRobotRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RobotRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(robotrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RobotRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RobotRequest), err
}
