// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/main/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTravelTimeCalculations implements TravelTimeCalculationInterface
type FakeTravelTimeCalculations struct {
	Fake *FakeEwmV1alpha1
	ns   string
}

var traveltimecalculationsResource = schema.GroupVersionResource{Group: "ewm.sap.com", Version: "v1alpha1", Resource: "traveltimecalculations"}

var traveltimecalculationsKind = schema.GroupVersionKind{Group: "ewm.sap.com", Version: "v1alpha1", Kind: "TravelTimeCalculation"}

// Get takes name of the travelTimeCalculation, and returns the corresponding travelTimeCalculation object, and an error if there is any.
func (c *FakeTravelTimeCalculations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TravelTimeCalculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(traveltimecalculationsResource, c.ns, name), &v1alpha1.TravelTimeCalculation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TravelTimeCalculation), err
}

// List takes label and field selectors, and returns the list of TravelTimeCalculations that match those selectors.
func (c *FakeTravelTimeCalculations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TravelTimeCalculationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(traveltimecalculationsResource, traveltimecalculationsKind, c.ns, opts), &v1alpha1.TravelTimeCalculationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TravelTimeCalculationList{ListMeta: obj.(*v1alpha1.TravelTimeCalculationList).ListMeta}
	for _, item := range obj.(*v1alpha1.TravelTimeCalculationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested travelTimeCalculations.
func (c *FakeTravelTimeCalculations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(traveltimecalculationsResource, c.ns, opts))

}

// Create takes the representation of a travelTimeCalculation and creates it.  Returns the server's representation of the travelTimeCalculation, and an error, if there is any.
func (c *FakeTravelTimeCalculations) Create(ctx context.Context, travelTimeCalculation *v1alpha1.TravelTimeCalculation, opts v1.CreateOptions) (result *v1alpha1.TravelTimeCalculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(traveltimecalculationsResource, c.ns, travelTimeCalculation), &v1alpha1.TravelTimeCalculation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TravelTimeCalculation), err
}

// Update takes the representation of a travelTimeCalculation and updates it. Returns the server's representation of the travelTimeCalculation, and an error, if there is any.
func (c *FakeTravelTimeCalculations) Update(ctx context.Context, travelTimeCalculation *v1alpha1.TravelTimeCalculation, opts v1.UpdateOptions) (result *v1alpha1.TravelTimeCalculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(traveltimecalculationsResource, c.ns, travelTimeCalculation), &v1alpha1.TravelTimeCalculation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TravelTimeCalculation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTravelTimeCalculations) UpdateStatus(ctx context.Context, travelTimeCalculation *v1alpha1.TravelTimeCalculation, opts v1.UpdateOptions) (*v1alpha1.TravelTimeCalculation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(traveltimecalculationsResource, "status", c.ns, travelTimeCalculation), &v1alpha1.TravelTimeCalculation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TravelTimeCalculation), err
}

// Delete takes name of the travelTimeCalculation and deletes it. Returns an error if one occurs.
func (c *FakeTravelTimeCalculations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(traveltimecalculationsResource, c.ns, name), &v1alpha1.TravelTimeCalculation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTravelTimeCalculations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(traveltimecalculationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TravelTimeCalculationList{})
	return err
}

// Patch applies the patch and returns the patched travelTimeCalculation.
func (c *FakeTravelTimeCalculations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TravelTimeCalculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(traveltimecalculationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TravelTimeCalculation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TravelTimeCalculation), err
}
