// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWarehouseOrders implements WarehouseOrderInterface
type FakeWarehouseOrders struct {
	Fake *FakeEwmV1alpha1
	ns   string
}

var warehouseordersResource = schema.GroupVersionResource{Group: "ewm.sap.com", Version: "v1alpha1", Resource: "warehouseorders"}

var warehouseordersKind = schema.GroupVersionKind{Group: "ewm.sap.com", Version: "v1alpha1", Kind: "WarehouseOrder"}

// Get takes name of the warehouseOrder, and returns the corresponding warehouseOrder object, and an error if there is any.
func (c *FakeWarehouseOrders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WarehouseOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(warehouseordersResource, c.ns, name), &v1alpha1.WarehouseOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WarehouseOrder), err
}

// List takes label and field selectors, and returns the list of WarehouseOrders that match those selectors.
func (c *FakeWarehouseOrders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WarehouseOrderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(warehouseordersResource, warehouseordersKind, c.ns, opts), &v1alpha1.WarehouseOrderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WarehouseOrderList{ListMeta: obj.(*v1alpha1.WarehouseOrderList).ListMeta}
	for _, item := range obj.(*v1alpha1.WarehouseOrderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested warehouseOrders.
func (c *FakeWarehouseOrders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(warehouseordersResource, c.ns, opts))

}

// Create takes the representation of a warehouseOrder and creates it.  Returns the server's representation of the warehouseOrder, and an error, if there is any.
func (c *FakeWarehouseOrders) Create(ctx context.Context, warehouseOrder *v1alpha1.WarehouseOrder, opts v1.CreateOptions) (result *v1alpha1.WarehouseOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(warehouseordersResource, c.ns, warehouseOrder), &v1alpha1.WarehouseOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WarehouseOrder), err
}

// Update takes the representation of a warehouseOrder and updates it. Returns the server's representation of the warehouseOrder, and an error, if there is any.
func (c *FakeWarehouseOrders) Update(ctx context.Context, warehouseOrder *v1alpha1.WarehouseOrder, opts v1.UpdateOptions) (result *v1alpha1.WarehouseOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(warehouseordersResource, c.ns, warehouseOrder), &v1alpha1.WarehouseOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WarehouseOrder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWarehouseOrders) UpdateStatus(ctx context.Context, warehouseOrder *v1alpha1.WarehouseOrder, opts v1.UpdateOptions) (*v1alpha1.WarehouseOrder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(warehouseordersResource, "status", c.ns, warehouseOrder), &v1alpha1.WarehouseOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WarehouseOrder), err
}

// Delete takes name of the warehouseOrder and deletes it. Returns an error if one occurs.
func (c *FakeWarehouseOrders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(warehouseordersResource, c.ns, name), &v1alpha1.WarehouseOrder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWarehouseOrders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(warehouseordersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WarehouseOrderList{})
	return err
}

// Patch applies the patch and returns the patched warehouseOrder.
func (c *FakeWarehouseOrders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WarehouseOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(warehouseordersResource, c.ns, name, pt, data, subresources...), &v1alpha1.WarehouseOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WarehouseOrder), err
}
