// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/main/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOrderAuctions implements OrderAuctionInterface
type FakeOrderAuctions struct {
	Fake *FakeEwmV1alpha1
	ns   string
}

var orderauctionsResource = schema.GroupVersionResource{Group: "ewm.sap.com", Version: "v1alpha1", Resource: "orderauctions"}

var orderauctionsKind = schema.GroupVersionKind{Group: "ewm.sap.com", Version: "v1alpha1", Kind: "OrderAuction"}

// Get takes name of the orderAuction, and returns the corresponding orderAuction object, and an error if there is any.
func (c *FakeOrderAuctions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OrderAuction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(orderauctionsResource, c.ns, name), &v1alpha1.OrderAuction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderAuction), err
}

// List takes label and field selectors, and returns the list of OrderAuctions that match those selectors.
func (c *FakeOrderAuctions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OrderAuctionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(orderauctionsResource, orderauctionsKind, c.ns, opts), &v1alpha1.OrderAuctionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OrderAuctionList{ListMeta: obj.(*v1alpha1.OrderAuctionList).ListMeta}
	for _, item := range obj.(*v1alpha1.OrderAuctionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested orderAuctions.
func (c *FakeOrderAuctions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(orderauctionsResource, c.ns, opts))

}

// Create takes the representation of a orderAuction and creates it.  Returns the server's representation of the orderAuction, and an error, if there is any.
func (c *FakeOrderAuctions) Create(ctx context.Context, orderAuction *v1alpha1.OrderAuction, opts v1.CreateOptions) (result *v1alpha1.OrderAuction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(orderauctionsResource, c.ns, orderAuction), &v1alpha1.OrderAuction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderAuction), err
}

// Update takes the representation of a orderAuction and updates it. Returns the server's representation of the orderAuction, and an error, if there is any.
func (c *FakeOrderAuctions) Update(ctx context.Context, orderAuction *v1alpha1.OrderAuction, opts v1.UpdateOptions) (result *v1alpha1.OrderAuction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(orderauctionsResource, c.ns, orderAuction), &v1alpha1.OrderAuction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderAuction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOrderAuctions) UpdateStatus(ctx context.Context, orderAuction *v1alpha1.OrderAuction, opts v1.UpdateOptions) (*v1alpha1.OrderAuction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(orderauctionsResource, "status", c.ns, orderAuction), &v1alpha1.OrderAuction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderAuction), err
}

// Delete takes name of the orderAuction and deletes it. Returns an error if one occurs.
func (c *FakeOrderAuctions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(orderauctionsResource, c.ns, name), &v1alpha1.OrderAuction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOrderAuctions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(orderauctionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OrderAuctionList{})
	return err
}

// Patch applies the patch and returns the patched orderAuction.
func (c *FakeOrderAuctions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OrderAuction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(orderauctionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.OrderAuction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrderAuction), err
}
