// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/SAP/ewm-cloud-robotics/go/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Auctioneers returns a AuctioneerInformer.
	Auctioneers() AuctioneerInformer
	// OrderAuctions returns a OrderAuctionInformer.
	OrderAuctions() OrderAuctionInformer
	// OrderReservations returns a OrderReservationInformer.
	OrderReservations() OrderReservationInformer
	// RobotConfigurations returns a RobotConfigurationInformer.
	RobotConfigurations() RobotConfigurationInformer
	// RunTimeEstimations returns a RunTimeEstimationInformer.
	RunTimeEstimations() RunTimeEstimationInformer
	// WarehouseOrders returns a WarehouseOrderInformer.
	WarehouseOrders() WarehouseOrderInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Auctioneers returns a AuctioneerInformer.
func (v *version) Auctioneers() AuctioneerInformer {
	return &auctioneerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrderAuctions returns a OrderAuctionInformer.
func (v *version) OrderAuctions() OrderAuctionInformer {
	return &orderAuctionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrderReservations returns a OrderReservationInformer.
func (v *version) OrderReservations() OrderReservationInformer {
	return &orderReservationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RobotConfigurations returns a RobotConfigurationInformer.
func (v *version) RobotConfigurations() RobotConfigurationInformer {
	return &robotConfigurationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RunTimeEstimations returns a RunTimeEstimationInformer.
func (v *version) RunTimeEstimations() RunTimeEstimationInformer {
	return &runTimeEstimationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WarehouseOrders returns a WarehouseOrderInformer.
func (v *version) WarehouseOrders() WarehouseOrderInformer {
	return &warehouseOrderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
