## Check the Cloud Robotics documentation for more information about deploying applications to the apps.cloudrobotics.com/v1alpha1 API
##
##

---
apiVersion: apps.cloudrobotics.com/v1alpha1
kind: AppRollout
metadata:
  name: ewm-base-robot
  namespace: default
  labels:
    app: ewm-base-robot
spec:
  appName: ewm-base-robot-$APP_VERSION
  robots:
  - selector:
      any: true
    values:
      missionCRD:
        enabled: false
