// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned"
	ewmv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/ewm/v1alpha1"
	fakeewmv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/ewm/v1alpha1/fake"
	missionv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/mission/v1alpha1"
	fakemissionv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/mission/v1alpha1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// EwmV1alpha1 retrieves the EwmV1alpha1Client
func (c *Clientset) EwmV1alpha1() ewmv1alpha1.EwmV1alpha1Interface {
	return &fakeewmv1alpha1.FakeEwmV1alpha1{Fake: &c.Fake}
}

// MissionV1alpha1 retrieves the MissionV1alpha1Client
func (c *Clientset) MissionV1alpha1() missionv1alpha1.MissionV1alpha1Interface {
	return &fakemissionv1alpha1.FakeMissionV1alpha1{Fake: &c.Fake}
}
