apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-monitoring-ui-{{ .Values.tenant }}
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServiceClassRef:
    name: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    oauth2-configuration:
      redirect-uris:
      - https://monitoring-ui.{{ .Values.tenant_domain }}/oauth/callback
      - http://localhost:8000/oauth/callback
    role-templates:
    - description: Supervise warehouse activities
      name: WarehouseSupervisor
      scope-references:
      - $XSAPPNAME.Edit
    scopes:
    - description: edit
      name: $XSAPPNAME.Edit
    xsappname: monitoring-ui-{{ .Values.tenant }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: monitoring-ui-credentials
spec:
  instanceRef:
    name: xsuaa-monitoring-ui-{{ .Values.tenant }}
  parameters: {}
  secretName: monitoring-ui-credentials
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-app-auth-proxy-bind
  labels:
    app: app-auth-proxy
spec:
  instanceRef:
    name: xsuaa-monitoring-ui-{{ .Values.tenant }}
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-app-auth-proxy-bind-usage
  labels:
    app: app-auth-proxy
spec:
  serviceBindingRef:
    name: xsuaa-app-auth-proxy-bind
  usedBy:
    kind: deployment
    name: app-auth-proxy
  parameters:
    envPrefix:
      name: "IDP_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-auth-proxy
  template:
    metadata:
      labels:
        app: app-auth-proxy
      annotations:
        # Checksum that pod restarts on config map changes
        checksum/config: {{ include (print $.Template.BasePath "/app-router-config.yaml") . | sha256sum }}
    spec:
      containers:
        - image: "{{ .Values.registry }}/{{ .Values.images.app_auth_proxy }}"
          name: app-auth-proxy
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: app-auth-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: app-auth-proxy
