{{ if and (eq .Values.sap_btp_service_operator "true") (eq .Values.use_istio "true") }}
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: xsuaa-monitoring-ui-{{ .Values.tenant }}
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    oauth2-configuration:
      redirect-uris:
      - https://monitoring-ui.{{ .Values.tenant_domain }}/oauth/callback
      - http://localhost:8000/oauth/callback
    role-templates:
    - description: Supervise warehouse activities
      name: WarehouseSupervisor
      scope-references:
      - $XSAPPNAME.Edit
    scopes:
    - description: edit
      name: $XSAPPNAME.Edit
    xsappname: monitoring-ui-{{ .Values.tenant }}
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: xsuaa-app-auth-proxy-bind
  labels:
    app: app-auth-proxy
spec:
  secretName: xsuaa-app-auth-proxy-bind
  serviceInstanceName: xsuaa-monitoring-ui-{{ .Values.tenant }}
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-app-auth-proxy-bind-usage
  labels:
    app: app-auth-proxy
spec:
  serviceBindingRef:
    name: xsuaa-app-auth-proxy-bind
  usedBy:
    kind: deployment
    name: app-auth-proxy
  parameters:
    envPrefix:
      name: "IDP_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-auth-proxy
  template:
    metadata:
      labels:
        app: app-auth-proxy
      annotations:
        # Checksum that pod restarts on config map changes
        checksum/config: {{ include (print $.Template.BasePath "/app-router-config.yaml") . | sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.registry }}/{{ .Values.images.app_auth_proxy }}"
        name: app-auth-proxy
        env:
        - name: IDP_clientid
          valueFrom:
            secretKeyRef:
              name: xsuaa-app-auth-proxy-bind
              key: clientid
        - name: IDP_clientsecret
          valueFrom:
            secretKeyRef:
              name: xsuaa-app-auth-proxy-bind
              key: clientsecret
        - name: IDP_url
          valueFrom:
            secretKeyRef:
              name: xsuaa-app-auth-proxy-bind
              key: url
        - name: IDP_token_endpoint_auth_method
          value: client_secret_post
        - name: IDP_xsappname
          valueFrom:
            secretKeyRef:
              name: xsuaa-app-auth-proxy-bind
              key: xsappname
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: app-auth-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: app-auth-proxy
{{ end }}