// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

package v2

// GetPath represents the result of GET /paths/{guid} endpoint
type GetPath struct {
	Autogenerated bool    `json:"autogenerated,omitempty"`
	Footprint     string  `json:"footprint,omitempty"`
	GoalPos       string  `json:"goal_pos,omitempty"`
	GoalPosID     string  `json:"goal_pos_id,omitempty"`
	GUID          string  `json:"guid,omitempty"`
	LastUsed      Time    `json:"last_used,omitempty"`
	Length        float64 `json:"length,omitempty"`
	MapCRC        string  `json:"map_crc,omitempty"`
	Path          string  `json:"path,omitempty"`
	StartPos      string  `json:"start_pos,omitempty"`
	StartPosID    string  `json:"start_pos_id,omitempty"`
	Time          float64 `json:"time,omitempty"`
	Valid         bool    `json:"valid,omitempty"`
}

// MirResponse identifies data type as MiR response
func (p *GetPath) MirResponse() {}

// GetPathsItem represents an item from result array of GET /paths endpoint
type GetPathsItem struct {
	GoalPos  string `json:"goal_pos,omitempty"`
	GUID     string `json:"guid,omitempty"`
	StartPos string `json:"start_pos,omitempty"`
	URL      string `json:"url,omitempty"`
}

// GetPaths represents the result array of GET /paths endpoint
type GetPaths []GetPathsItem

// MirResponse identifies data type as MiR response
func (p *GetPaths) MirResponse() {}
