# Simulated EWM OData API server that produces a never ending stream of warehouse orders/tasks

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewm-sim
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ewm-sim
  template:
    metadata:
      labels:
        app: ewm-sim
    spec:
      containers:
      - name: ewm-sim
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
          name: odata-api
        env:
        - name: ODATA_USER
          value: {{ .Values.envs.ewm.user }} 
        - name: ODATA_PASSWD
          value: {{ .Values.envs.ewm.password }} 
        - name: GEN_INT
          value: {{ .Values.envs.ewm.geninterval }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
---
kind: Service
apiVersion: v1
metadata:
  name: ewm-sim
  labels:
    app: ewm-sim
spec:
  selector:
    app: ewm-sim
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: odata-api
  type: ClusterIP
---
