// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MissionListerExpansion allows custom methods to be added to
// MissionLister.
type MissionListerExpansion interface{}

// MissionNamespaceListerExpansion allows custom methods to be added to
// MissionNamespaceLister.
type MissionNamespaceListerExpansion interface{}
