// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/main/LICENSE)
//

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"

	ewmv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/ewm/v1alpha1"
	missionv1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/client/clientset/versioned/typed/mission/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	EwmV1alpha1() ewmv1alpha1.EwmV1alpha1Interface
	MissionV1alpha1() missionv1alpha1.MissionV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	ewmV1alpha1     *ewmv1alpha1.EwmV1alpha1Client
	missionV1alpha1 *missionv1alpha1.MissionV1alpha1Client
}

// EwmV1alpha1 retrieves the EwmV1alpha1Client
func (c *Clientset) EwmV1alpha1() ewmv1alpha1.EwmV1alpha1Interface {
	return c.ewmV1alpha1
}

// MissionV1alpha1 retrieves the MissionV1alpha1Client
func (c *Clientset) MissionV1alpha1() missionv1alpha1.MissionV1alpha1Interface {
	return c.missionV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.ewmV1alpha1, err = ewmv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.missionV1alpha1, err = missionv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.ewmV1alpha1 = ewmv1alpha1.NewForConfigOrDie(c)
	cs.missionV1alpha1 = missionv1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.ewmV1alpha1 = ewmv1alpha1.New(c)
	cs.missionV1alpha1 = missionv1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
