FROM node:lts-alpine

RUN adduser -D -g '' appuser

RUN apk upgrade --update-cache --available && \
    apk add chromium && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

WORKDIR /app

RUN mkdir cert && \
    cd cert && \
    openssl req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj '/CN=localhost' && \
    cd ../ && \
    chown -R appuser:appuser cert/ && \
    chmod 755 cert/

RUN npm i -g @ui5/cli && \
    npm i -g concurrently

COPY app/package.json /app/package.json
COPY app/package-lock.json /app/package-lock.json

RUN npm i --no-optional 

COPY app /app/

RUN npm run-script build && \
    rm -rf webapp/

USER appuser

EXPOSE 8080 8081 8000

CMD [ "concurrently", "--no-color", "--kill-others", "\"node ui5server.js\"", "\"node exposedserver.js\"", "\"node dummyclient.js\"", "\"node tools/waitForServer.js test\"" ]