replicaCount: 1

image:
  repository: "ewmcloudrobotics/order-manager"
  tag: "latest"

envs:
  ewmuser: ""
  ewmhost: ""
  ewmauth: "Basic"
  ewmpassword: ""
  ewmbasepath: "/odata/SAP/ZEWM_ROBCO_SRV"
  ewmclientid: ""
  ewmclientsecret: ""
  ewmtokenendpoint: ""
  reservationtimeout: 5.0

robot:
  name: ""