image: "ewmcloudrobotics/order-manager:latest"

tenant_main_namespace: "default"
tenant: "t"

envs:
  ewmuser: ""
  ewmhost: ""
  ewmauth: "Basic"
  ewmpassword: ""
  ewmbasepath: "/odata/SAP/ZEWM_ROBCO_SRV"
  ewmclientid: ""
  ewmclientsecret: ""
  ewmtokenendpoint: ""
  reservationtimeout: 5.0
  log:
    level: "info"
    format: "json"
