// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AuctioneerRequestLister helps list AuctioneerRequests.
type AuctioneerRequestLister interface {
	// List lists all AuctioneerRequests in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.AuctioneerRequest, err error)
	// AuctioneerRequests returns an object that can list and get AuctioneerRequests.
	AuctioneerRequests(namespace string) AuctioneerRequestNamespaceLister
	AuctioneerRequestListerExpansion
}

// auctioneerRequestLister implements the AuctioneerRequestLister interface.
type auctioneerRequestLister struct {
	indexer cache.Indexer
}

// NewAuctioneerRequestLister returns a new AuctioneerRequestLister.
func NewAuctioneerRequestLister(indexer cache.Indexer) AuctioneerRequestLister {
	return &auctioneerRequestLister{indexer: indexer}
}

// List lists all AuctioneerRequests in the indexer.
func (s *auctioneerRequestLister) List(selector labels.Selector) (ret []*v1alpha1.AuctioneerRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AuctioneerRequest))
	})
	return ret, err
}

// AuctioneerRequests returns an object that can list and get AuctioneerRequests.
func (s *auctioneerRequestLister) AuctioneerRequests(namespace string) AuctioneerRequestNamespaceLister {
	return auctioneerRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AuctioneerRequestNamespaceLister helps list and get AuctioneerRequests.
type AuctioneerRequestNamespaceLister interface {
	// List lists all AuctioneerRequests in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.AuctioneerRequest, err error)
	// Get retrieves the AuctioneerRequest from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.AuctioneerRequest, error)
	AuctioneerRequestNamespaceListerExpansion
}

// auctioneerRequestNamespaceLister implements the AuctioneerRequestNamespaceLister
// interface.
type auctioneerRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AuctioneerRequests in the indexer for a given namespace.
func (s auctioneerRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AuctioneerRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AuctioneerRequest))
	})
	return ret, err
}

// Get retrieves the AuctioneerRequest from the indexer for a given namespace and name.
func (s auctioneerRequestNamespaceLister) Get(name string) (*v1alpha1.AuctioneerRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("auctioneerrequest"), name)
	}
	return obj.(*v1alpha1.AuctioneerRequest), nil
}
