// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuctioneerListerExpansion allows custom methods to be added to
// AuctioneerLister.
type AuctioneerListerExpansion interface{}

// AuctioneerNamespaceListerExpansion allows custom methods to be added to
// AuctioneerNamespaceLister.
type AuctioneerNamespaceListerExpansion interface{}

// OrderAuctionListerExpansion allows custom methods to be added to
// OrderAuctionLister.
type OrderAuctionListerExpansion interface{}

// OrderAuctionNamespaceListerExpansion allows custom methods to be added to
// OrderAuctionNamespaceLister.
type OrderAuctionNamespaceListerExpansion interface{}

// OrderReservationListerExpansion allows custom methods to be added to
// OrderReservationLister.
type OrderReservationListerExpansion interface{}

// OrderReservationNamespaceListerExpansion allows custom methods to be added to
// OrderReservationNamespaceLister.
type OrderReservationNamespaceListerExpansion interface{}

// RobotConfigurationListerExpansion allows custom methods to be added to
// RobotConfigurationLister.
type RobotConfigurationListerExpansion interface{}

// RobotConfigurationNamespaceListerExpansion allows custom methods to be added to
// RobotConfigurationNamespaceLister.
type RobotConfigurationNamespaceListerExpansion interface{}

// TravelTimeCalculationListerExpansion allows custom methods to be added to
// TravelTimeCalculationLister.
type TravelTimeCalculationListerExpansion interface{}

// TravelTimeCalculationNamespaceListerExpansion allows custom methods to be added to
// TravelTimeCalculationNamespaceLister.
type TravelTimeCalculationNamespaceListerExpansion interface{}

// WarehouseOrderListerExpansion allows custom methods to be added to
// WarehouseOrderLister.
type WarehouseOrderListerExpansion interface{}

// WarehouseOrderNamespaceListerExpansion allows custom methods to be added to
// WarehouseOrderNamespaceLister.
type WarehouseOrderNamespaceListerExpansion interface{}
