// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuctioneerListerExpansion allows custom methods to be added to
// AuctioneerLister.
type AuctioneerListerExpansion interface{}

// AuctioneerNamespaceListerExpansion allows custom methods to be added to
// AuctioneerNamespaceLister.
type AuctioneerNamespaceListerExpansion interface{}

// AuctioneerRequestListerExpansion allows custom methods to be added to
// AuctioneerRequestLister.
type AuctioneerRequestListerExpansion interface{}

// AuctioneerRequestNamespaceListerExpansion allows custom methods to be added to
// AuctioneerRequestNamespaceLister.
type AuctioneerRequestNamespaceListerExpansion interface{}

// OrderAuctionListerExpansion allows custom methods to be added to
// OrderAuctionLister.
type OrderAuctionListerExpansion interface{}

// OrderAuctionNamespaceListerExpansion allows custom methods to be added to
// OrderAuctionNamespaceLister.
type OrderAuctionNamespaceListerExpansion interface{}

// RobotConfigurationListerExpansion allows custom methods to be added to
// RobotConfigurationLister.
type RobotConfigurationListerExpansion interface{}

// RobotConfigurationNamespaceListerExpansion allows custom methods to be added to
// RobotConfigurationNamespaceLister.
type RobotConfigurationNamespaceListerExpansion interface{}

// RobotRequestListerExpansion allows custom methods to be added to
// RobotRequestLister.
type RobotRequestListerExpansion interface{}

// RobotRequestNamespaceListerExpansion allows custom methods to be added to
// RobotRequestNamespaceLister.
type RobotRequestNamespaceListerExpansion interface{}

// WarehouseOrderListerExpansion allows custom methods to be added to
// WarehouseOrderLister.
type WarehouseOrderListerExpansion interface{}

// WarehouseOrderNamespaceListerExpansion allows custom methods to be added to
// WarehouseOrderNamespaceLister.
type WarehouseOrderNamespaceListerExpansion interface{}
