// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RobotRequestLister helps list RobotRequests.
type RobotRequestLister interface {
	// List lists all RobotRequests in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.RobotRequest, err error)
	// RobotRequests returns an object that can list and get RobotRequests.
	RobotRequests(namespace string) RobotRequestNamespaceLister
	RobotRequestListerExpansion
}

// robotRequestLister implements the RobotRequestLister interface.
type robotRequestLister struct {
	indexer cache.Indexer
}

// NewRobotRequestLister returns a new RobotRequestLister.
func NewRobotRequestLister(indexer cache.Indexer) RobotRequestLister {
	return &robotRequestLister{indexer: indexer}
}

// List lists all RobotRequests in the indexer.
func (s *robotRequestLister) List(selector labels.Selector) (ret []*v1alpha1.RobotRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RobotRequest))
	})
	return ret, err
}

// RobotRequests returns an object that can list and get RobotRequests.
func (s *robotRequestLister) RobotRequests(namespace string) RobotRequestNamespaceLister {
	return robotRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RobotRequestNamespaceLister helps list and get RobotRequests.
type RobotRequestNamespaceLister interface {
	// List lists all RobotRequests in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.RobotRequest, err error)
	// Get retrieves the RobotRequest from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.RobotRequest, error)
	RobotRequestNamespaceListerExpansion
}

// robotRequestNamespaceLister implements the RobotRequestNamespaceLister
// interface.
type robotRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RobotRequests in the indexer for a given namespace.
func (s robotRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RobotRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RobotRequest))
	})
	return ret, err
}

// Get retrieves the RobotRequest from the indexer for a given namespace and name.
func (s robotRequestNamespaceLister) Get(name string) (*v1alpha1.RobotRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("robotrequest"), name)
	}
	return obj.(*v1alpha1.RobotRequest), nil
}
