// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RunTimeEstimationLister helps list RunTimeEstimations.
type RunTimeEstimationLister interface {
	// List lists all RunTimeEstimations in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.RunTimeEstimation, err error)
	// RunTimeEstimations returns an object that can list and get RunTimeEstimations.
	RunTimeEstimations(namespace string) RunTimeEstimationNamespaceLister
	RunTimeEstimationListerExpansion
}

// runTimeEstimationLister implements the RunTimeEstimationLister interface.
type runTimeEstimationLister struct {
	indexer cache.Indexer
}

// NewRunTimeEstimationLister returns a new RunTimeEstimationLister.
func NewRunTimeEstimationLister(indexer cache.Indexer) RunTimeEstimationLister {
	return &runTimeEstimationLister{indexer: indexer}
}

// List lists all RunTimeEstimations in the indexer.
func (s *runTimeEstimationLister) List(selector labels.Selector) (ret []*v1alpha1.RunTimeEstimation, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RunTimeEstimation))
	})
	return ret, err
}

// RunTimeEstimations returns an object that can list and get RunTimeEstimations.
func (s *runTimeEstimationLister) RunTimeEstimations(namespace string) RunTimeEstimationNamespaceLister {
	return runTimeEstimationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RunTimeEstimationNamespaceLister helps list and get RunTimeEstimations.
type RunTimeEstimationNamespaceLister interface {
	// List lists all RunTimeEstimations in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.RunTimeEstimation, err error)
	// Get retrieves the RunTimeEstimation from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.RunTimeEstimation, error)
	RunTimeEstimationNamespaceListerExpansion
}

// runTimeEstimationNamespaceLister implements the RunTimeEstimationNamespaceLister
// interface.
type runTimeEstimationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RunTimeEstimations in the indexer for a given namespace.
func (s runTimeEstimationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RunTimeEstimation, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RunTimeEstimation))
	})
	return ret, err
}

// Get retrieves the RunTimeEstimation from the indexer for a given namespace and name.
func (s runTimeEstimationNamespaceLister) Get(name string) (*v1alpha1.RunTimeEstimation, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runtimeestimation"), name)
	}
	return obj.(*v1alpha1.RunTimeEstimation), nil
}
