// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
//
// This file is part of ewm-cloud-robotics
// (see https://github.com/SAP/ewm-cloud-robotics).
//
// This file is licensed under the Apache Software License, v. 2 except as noted
// otherwise in the LICENSE file (https://github.com/SAP/ewm-cloud-robotics/blob/master/LICENSE)
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/ewm-cloud-robotics/go/pkg/apis/ewm/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WarehouseOrderLister helps list WarehouseOrders.
type WarehouseOrderLister interface {
	// List lists all WarehouseOrders in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.WarehouseOrder, err error)
	// WarehouseOrders returns an object that can list and get WarehouseOrders.
	WarehouseOrders(namespace string) WarehouseOrderNamespaceLister
	WarehouseOrderListerExpansion
}

// warehouseOrderLister implements the WarehouseOrderLister interface.
type warehouseOrderLister struct {
	indexer cache.Indexer
}

// NewWarehouseOrderLister returns a new WarehouseOrderLister.
func NewWarehouseOrderLister(indexer cache.Indexer) WarehouseOrderLister {
	return &warehouseOrderLister{indexer: indexer}
}

// List lists all WarehouseOrders in the indexer.
func (s *warehouseOrderLister) List(selector labels.Selector) (ret []*v1alpha1.WarehouseOrder, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WarehouseOrder))
	})
	return ret, err
}

// WarehouseOrders returns an object that can list and get WarehouseOrders.
func (s *warehouseOrderLister) WarehouseOrders(namespace string) WarehouseOrderNamespaceLister {
	return warehouseOrderNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// WarehouseOrderNamespaceLister helps list and get WarehouseOrders.
type WarehouseOrderNamespaceLister interface {
	// List lists all WarehouseOrders in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.WarehouseOrder, err error)
	// Get retrieves the WarehouseOrder from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.WarehouseOrder, error)
	WarehouseOrderNamespaceListerExpansion
}

// warehouseOrderNamespaceLister implements the WarehouseOrderNamespaceLister
// interface.
type warehouseOrderNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all WarehouseOrders in the indexer for a given namespace.
func (s warehouseOrderNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.WarehouseOrder, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WarehouseOrder))
	})
	return ret, err
}

// Get retrieves the WarehouseOrder from the indexer for a given namespace and name.
func (s warehouseOrderNamespaceLister) Get(name string) (*v1alpha1.WarehouseOrder, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("warehouseorder"), name)
	}
	return obj.(*v1alpha1.WarehouseOrder), nil
}
