apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sap-ewm:read-crds
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
