apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sap-ewm:robot-controller
rules:
- apiGroups:
  - registry.cloudrobotics.com
  resources:
  - robots
  - robots/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mission.cloudrobotics.com
  resources:
  - missions
  - missions/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mission.cloudrobotics.com
  resources:
  - missions/status
  verbs:
  - update
  - patch
- apiGroups:
  - ewm.sap.com
  resources:
  - warehouseorders
  - warehouseorders/status
  - robotconfigurations
  - robotconfigurations/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ewm.sap.com
  resources:
  - warehouseorders/status
  - robotconfigurations/status
  verbs:
  - update
  - patch
