apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: auctioneerrequests.sap.com
spec:
  # list of versions supported by this CustomResourceDefinition
  group: sap.com
  # list of versions supported by this CustomResourceDefinition
  version: v1
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  # subresources:
  #   status: {}
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: auctioneerrequests
    # singular name to be used as an alias on the CLI and for display
    singular: auctioneerrequest
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AuctioneerRequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - auceq
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - orderrequest
          properties:
            orderrequest:
              type: object
              required:
                - lgnum
                - rsrctype
                - rsrcgrp
                - quantity
              properties:
                lgnum:
                  type: string
                rsrctype:
                  type: string
                rsrcgrp:
                  type: string
                quantity:
                  type: integer
                  minimum: 0
            orderassignment:
              type: array
              items:
                type: object
                properties:
                  lgnum:
                    type: string
                  who:
                    type: string
                  rsrc:
                    type: string
        status:
          type: object
          properties:
            warehouseorders:
              type: array
              items:
                type: object
                properties:
                  lgnum:
                    type: string
                  who:
                    type: string
            orderassignment:
              type: array
              items:
                type: object
                properties:
                  lgnum:
                    type: string
                  who:
                    type: string
                  rsrc:
                    type: string
            status:
              type: string
              enum:
                - NEW
                - ACCEPTED
                - RESERVATIONS
                - FAILED
                - SUCCEEDED
                - TIMEOUT
            message:
              type: string
            validuntil:
              type: string
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.validuntil
    name: Valid until
    type: date
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
