apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: traveltimecalculations.ewm.sap.com
spec:
  group: ewm.sap.com
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: traveltimecalculations
    # singular name to be used as an alias on the CLI and for display
    singular: traveltimecalculation
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TravelTimeCalculation
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ttc
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - paths
                - startPosition
                - validuntil
              properties:
                paths:
                  type: array
                  items:
                    type: object
                    required:
                      - start
                      - goal
                    properties:
                      start:
                        type: string
                      goal:
                        type: string
                startPosition:
                  type: string
                validuntil:
                  type: string
            status:
              type: object
              properties:
                runtimes:
                  type: array
                  items:
                    type: object
                    required:
                      - start
                      - goal
                      - time
                    properties:
                      start:
                        type: string
                      goal:
                        type: string
                      time:
                        type: number
                status:
                  type: string
                  enum:
                    - RUNNING
                    - PROCESSED