---
apiVersion: registry.cloudrobotics.com/v1alpha1
kind: RobotType
metadata:
  name: {{ .Values.robotMetadata.type }}
spec:
  make: {{ .Values.robotMetadata.make }}
  model: {{ .Values.robotMetadata.model }}
---
{{- range $i, $e := untilStep 1 (int (add1 $.Values.numberdummyrobots)) 1 }}
apiVersion: registry.cloudrobotics.com/v1alpha1
kind: Robot
metadata:
  name: "dummy-{{ trunc -4 (printf "0000%v" $e) }}"
  labels:
    cloudrobotics.com/robot-name: "dummy-{{ trunc -4 (printf "0000%v" $e) }}"
    ewmRobotController: {{ $.Values.robotMetadata.ewmRobotController }}
    ewmRobotControllerCloud: {{ $.Values.robotMetadata.ewmRobotControllerCloud }}
    model: {{ $.Values.robotMetadata.model }}
    make: {{ $.Values.robotMetadata.make }}
spec:
  project: {{ $.Values.project }}
  type: {{ $.Values.robotMetadata.type }}
---
{{- end }}
