apiVersion: v1
kind: Secret
metadata:
  name: ewm-odata-api
type: Opaque
## Usage of 'stringData' field rather than 'data' to leverage automatic base64 en-/decoding 
## (ref. https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually)
stringData:
  ewmhost: "{{ .Values.envs.ewmhost }}"
  ewmauth: "{{ .Values.envs.ewmauth }}"
  ewmuser: "{{ .Values.envs.ewmuser }}"
  ewmpswd: "{{ .Values.envs.ewmpassword }}"
  ewmpath: "{{ .Values.envs.ewmbasepath }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
      - image: {{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}
        imagePullPolicy: Always
        name: order-manager
        env:
        - name: EWM_USER
          valueFrom:
            secretKeyRef:
              name: ewm-odata-api
              key: ewmuser
        - name: EWM_HOST
          valueFrom:
            secretKeyRef:
              name: ewm-odata-api
              key: ewmhost
        - name: EWM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ewm-odata-api
              key: ewmpswd
        - name: EWM_AUTH
          valueFrom:
            secretKeyRef:
              name: ewm-odata-api
              key: ewmauth
        - name: EWM_BASEPATH
          valueFrom:
            secretKeyRef:
              name: ewm-odata-api
              key: ewmpath
        - name: EWM_LGNUM
          value: "{{ .Values.envs.ewmlgnum }}"
        - name: EWM_RSRC_TYPE
          value: "{{ .Values.envs.ewmrsrctype }}"
        - name: EWM_RSRC_GRP
          value: "{{ .Values.envs.ewmrsrcgrp }}"
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager
  labels:
    app: order-manager
spec:
  ports:
  - name: metrics
    port: 8000
  selector:
    app: order-manager
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-manager
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: order-manager
