apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: missions.mission.cloudrobotics.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: mission.cloudrobotics.com
  names:
    kind: Mission
    listKind: MissionList
    plural: missions
    singular: mission
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          maxProperties: 2
          properties:
            actions:
              items:
                oneOf:
                - maxProperties: 1
                  properties:
                    charge:
                      maxProperties: 3
                      properties:
                        chargerName:
                          type: string
                        targetBatteryPercent:
                          maximum: 100
                          minimum: 0
                          type: integer
                        thresholdBatteryPercent:
                          maximum: 100
                          minimum: 0
                          type: integer
                      required:
                      - chargerName
                      - thresholdBatteryPercent
                      - targetBatteryPercent
                      type: object
                  required:
                  - charge
                  type: object
                - maxProperties: 1
                  properties:
                    moveToNamedPosition:
                      maxProperties: 1
                      properties:
                        targetName:
                          type: string
                      required:
                      - targetName
                      type: object
                  required:
                  - moveToNamedPosition
                  type: object
                - maxProperties: 1
                  properties:
                    getTrolley:
                      maxProperties: 1
                      properties:
                        dockName:
                          type: string
                      required:
                      - dockName
                      type: object
                  required:
                  - getTrolley
                  type: object
                - maxProperties: 1
                  properties:
                    returnTrolley:
                      maxProperties: 1
                      properties:
                        dockName:
                          type: string
                      required:
                      - dockName
                      type: object
                  required:
                  - returnTrolley
                  type: object
              type: array
            timeOutSec:
              minimum: 0
              type: integer
          required:
          - actions
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true