name: build-ewm-cloud-robotics-images

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'docs/**'
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install skaffold /usr/local/bin/ && \
        rm -f skaffold

    - name: Install tests/container-structure-test
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
        chmod +x container-structure-test-linux-amd64 && \
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: lowercase repo
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}

    - name: Build and push images with v20060102-gitSHA tag
      run: skaffold run --default-repo ghcr.io/${REPO} -p push-all

    - name: Push images with latest tag
      run: skaffold run --default-repo ghcr.io/${REPO} -p push-all-latest --skip-tests=true